apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-bdb61f45943d43cdb27924d2fbf0f667-depl
  labels:
    app: coll-bdb61f45943d43cdb27924d2fbf0f667
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-bdb61f45943d43cdb27924d2fbf0f667
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-bdb61f45943d43cdb27924d2fbf0f667
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-bdb61f45943d43cdb27924d2fbf0f667
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-bdb61f45943d43cdb27924d2fbf0f667
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping